### PR TITLE
Update Read-JsonConfigFile.ps1

### LINKED ISSUE #45: Change missing property to warning
https://github.com/SQLPlayer/azure.datafactory.tools/blob/1398e3db73cf5067a149f4d010d7a65e0985e9e8/private/Read-JsonConfigFile.ps1#L37

Is it possible to change this to a warning, so that the script can continue to execute? We have multiple ADFs that we would like to use a single JSON configuration file - many properties are repeated between them, but sometimes ADFs won't have all of them. It could be a flag to indicate that we don't mind skipping missing properties?

### PR DESCRIPTION
**Pull request by chris5287**
Fixes #45

### CODE REVIEW

**Comment by NowinskiK** [comment]
Hi Chris. I would be happy to accept this PR, but unfortunately, I can not in this form.
The change can't be a breaking change of changing the behaviour of the existing functionality.
In other words, please add `$FailsWhenConfigItemNotFound` parameter to `AdfPublishOption` class and check it accordingly in `Read-JsonConfigFile` cmdlet.

**Comment by chris5287** [comment]
@NowinskiK I've made some changes, but unsure how to run the tests?

**Comment by NowinskiK** [comment]
In folder `test` you'll find script `!RunAllTests.ps1`

**Comment by chris5287** [comment]
@NowinskiK do I just need to create a `rg-devops-factory` resource group to run the tests, as I get a lot of errors? If so, assume I can just delete this at the end and all resources will be deleted?

**Comment by NowinskiK** [comment]
Yes, you need to create that RG (or another one and replace the name in the code).
The Resource Group will not be automatically deleted and tests create ADF instance only AFAIR.

**Comment by chris5287** [comment]
@NowinskiK after realising the GUID used for DataFactoryName was hard coded (so the test were failing due to the Data Factory already existing in someone else's subscription) I've been able to run the tests but I'm seeing some failures even in the master branch without my changes, is this expected?

image

**Comment by NowinskiK** [comment]
All tests should pass with success. I run CI (build) pipeline based on your code (PR) and it's fine:
image
The last 2 things:  
1) Please update the documentation with a new option available
2) Are you able to add new test class for testing function `Read-JsonConfigFile` (similar to `Read-CsvConfigFile.Tests.ps1`) due to your changes?
If so, I'd suggest only 3 test cases as a minimum:
a) function Should exist
b) When call and object does not exist and $FailsWhenConfigItemNotFound=True -> should Throw an error
c) When call and object does not exist and $FailsWhenConfigItemNotFound=False -> should NOT Throw an error

**Comment by chris5287** [comment]
@NowinskiK added tests and documentation as requested 😄

**Pull request merged**
