### PR TITLE
Add option to index into arrays by element name - Issue #98

### PR DESCRIPTION
**Pull request by NJLangley**
Hi Kamil

Here's the PR for Issue #98.

Added the option to update values on an object in an array by indexing into it using the name of the item. There are unit tests for the new functionality. The old functionality of using integer based indexing into the array still works too.

The implementation has a few limitations:
- Currently only arrays where all items within the array have a name property can be accessed using the name as the indexer. This is because it is implemented using dictionaries internally, and therefore requires a key. It is easy to add any other properties we may want to use as a key, there is an array of values to check, first value is highest priority.
- There is an edge case where changing the name of the item you access via a name based index means subsequent updates in the csv/json file must then use the new name. They are applied in order, again a limitation of the way it extends existing functionality. This edge case is covered in the test data.

The 3rd commit contains a few changes to the test structure that I was using to make it easier to debug locally. They should not change the way tests are run for anyone else or by CI, but make it a bit faster to debug from VSCode.

I have run all the unit tests locally, I have not run the integration tests yet.

### CODE REVIEW

**Comment by NJLangley** [comment]
Let me know if you want me to update the documentation

**Comment by NowinskiK** [comment]
That looks GREAT!
Thanks for adding unit tests.
Yes, update the doc as well, please. 
I will have a look at this and comment at weekend I hope.
Thanks for your contribution!

**Comment by NJLangley** [comment]
Updated the docs for the functionality.

**Comment by NowinskiK** [comment]
Thanks! I will merge it now. There are few more changes I'd like to include in the new release, so I will try to release it as soon as I can.

**Review by NowinskiK — APPROVED** [review]

**Pull request merged**
